import type { Trend } from "@/lib/types";

function days(n: number, base = 45): { day: string; score: number }[] {
  return Array.from({ length: 14 }, (_, i) => ({
    day: `Day ${i + 1}`,
    score: Math.min(100, base + Math.floor(Math.random() * n * (i / 7))),
  }));
}

export const MOCK_TRENDS: Trend[] = [
  {
    id: "t1",
    title: "AI-Generated Income: $10K/month with No Skills",
    niche: "AI",
    platform: "YouTube",
    country: "Global",
    viralScore: 94,
    opportunityScore: 88,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 2_400_000,
    engagementRate: 8.7,
    hookPattern: "Shocking income claim → Reveal AI tool → Step-by-step proof",
    editingStyle: "Fast cuts, screen recordings, reaction overlays",
    audienceBehavior: "High save rate, share to friends, comment with skepticism",
    growthData: days(18, 30),
    hashtags: ["#AIIncome", "#AITools", "#MakeMoneyOnline", "#AIAutomation"],
  },
  {
    id: "t2",
    title: "The Silent Vlog Trend: No Talking, Just Vibes",
    niche: "Lifestyle",
    platform: "TikTok",
    country: "Global",
    viralScore: 91,
    opportunityScore: 95,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 5_100_000,
    engagementRate: 12.3,
    hookPattern: "Aesthetic b-roll → ambient music → day-in-life montage",
    editingStyle: "Cinematic slow motion, color graded, no voiceover",
    audienceBehavior: "Massive saves, rewatch, calming response comments",
    growthData: days(22, 20),
    hashtags: ["#SilentVlog", "#DayInMyLife", "#AestheticVlog", "#Vlog"],
  },
  {
    id: "t3",
    title: "How I Invested $500 in Index Funds for 1 Year",
    niche: "Finance",
    platform: "YouTube",
    country: "USA",
    viralScore: 87,
    opportunityScore: 79,
    saturationLevel: "Medium",
    trendVelocity: "Rising",
    estimatedViews: 890_000,
    engagementRate: 6.2,
    hookPattern: "Exact dollar amount → time period → real results reveal",
    editingStyle: "Talking head + screen recording, clean B-roll",
    audienceBehavior: "Comment questions, bookmark for later, share to non-creators",
    growthData: days(12, 50),
    hashtags: ["#IndexFunds", "#Investing", "#PersonalFinance", "#PassiveIncome"],
  },
  {
    id: "t4",
    title: "Speedrun Cooking: Michelin-Star Meals in 60 Seconds",
    niche: "Lifestyle",
    platform: "TikTok",
    country: "Global",
    viralScore: 89,
    opportunityScore: 91,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 7_800_000,
    engagementRate: 14.1,
    hookPattern: "Impossibly fast cook → satisfying finish → viewer shock",
    editingStyle: "Hyperspeed timelapse, ASMR sounds, satisfying transitions",
    audienceBehavior: "Duet bait, saves recipe, comments 'I could never'",
    growthData: days(25, 15),
    hashtags: ["#CookingHacks", "#FoodTok", "#QuickRecipes", "#ChefLife"],
  },
  {
    id: "t5",
    title: "Cursor AI Builds My SaaS in 24 Hours",
    niche: "Tech",
    platform: "YouTube",
    country: "Global",
    viralScore: 92,
    opportunityScore: 84,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 1_200_000,
    engagementRate: 9.4,
    hookPattern: "AI does all the coding → real product launch → revenue reveal",
    editingStyle: "Screen recording with face cam, fast cuts, live reactions",
    audienceBehavior: "High comment engagement, saves, asks about specific AI tools",
    growthData: days(20, 25),
    hashtags: ["#CursorAI", "#BuildInPublic", "#SaaS", "#AIStartup"],
  },
  {
    id: "t6",
    title: "Debt-Free at 23: Exactly What I Did",
    niche: "Finance",
    platform: "Instagram",
    country: "USA",
    viralScore: 83,
    opportunityScore: 76,
    saturationLevel: "Medium",
    trendVelocity: "Rising",
    estimatedViews: 620_000,
    engagementRate: 7.8,
    hookPattern: "Age + outcome → backstory → actionable steps",
    editingStyle: "Carousel format, clean typography, relatable photos",
    audienceBehavior: "Save + share, tag partner/friends, ask follow-up questions",
    growthData: days(10, 55),
    hashtags: ["#DebtFree", "#FinancialFreedom", "#MoneyTips", "#PersonalFinance"],
  },
  {
    id: "t7",
    title: "Gaming Setup Tour: Under $300 Budget",
    niche: "Gaming",
    platform: "YouTube",
    country: "USA",
    viralScore: 79,
    opportunityScore: 85,
    saturationLevel: "Medium",
    trendVelocity: "Stable",
    estimatedViews: 450_000,
    engagementRate: 5.6,
    hookPattern: "Budget constraint → expectation subversion → impressive reveal",
    editingStyle: "Cinematic walkthrough, affiliate link callouts, product close-ups",
    audienceBehavior: "Comments setup questions, affiliate link clicks, share with friends",
    growthData: days(8, 60),
    hashtags: ["#GamingSetup", "#BudgetGaming", "#SetupTour", "#GamingRoom"],
  },
  {
    id: "t8",
    title: "Morning Routine That Increased My Productivity 10x",
    niche: "Lifestyle",
    platform: "YouTube",
    country: "Global",
    viralScore: 85,
    opportunityScore: 72,
    saturationLevel: "High",
    trendVelocity: "Stable",
    estimatedViews: 340_000,
    engagementRate: 4.9,
    hookPattern: "Productivity claim → specific routine → before/after results",
    editingStyle: "Aesthetic morning aesthetic, warm tones, journal overlays",
    audienceBehavior: "Save for motivation, comment own routines, high replays",
    growthData: days(6, 65),
    hashtags: ["#MorningRoutine", "#Productivity", "#DailyRoutine", "#SelfImprovement"],
  },
  {
    id: "t9",
    title: "AI Stocks That Could 10x in 2025",
    niche: "Investing",
    platform: "YouTube",
    country: "USA",
    viralScore: 88,
    opportunityScore: 82,
    saturationLevel: "Medium",
    trendVelocity: "Rising",
    estimatedViews: 980_000,
    engagementRate: 7.1,
    hookPattern: "10x claim → AI trend context → specific stock analysis",
    editingStyle: "Professional charts, talking head, data overlays",
    audienceBehavior: "High comment debate, saves, subscribes for updates",
    growthData: days(14, 45),
    hashtags: ["#AIStocks", "#Investing2025", "#StockMarket", "#AIInvesting"],
  },
  {
    id: "t10",
    title: "I Played Elden Ring Blindfolded and Won",
    niche: "Gaming",
    platform: "YouTube",
    country: "Global",
    viralScore: 96,
    opportunityScore: 70,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 3_200_000,
    engagementRate: 11.2,
    hookPattern: "Impossible challenge → live attempt → emotional climax",
    editingStyle: "Real-time gameplay, reaction close-ups, dramatic music sync",
    audienceBehavior: "High comment engagement, shares, clip reposting",
    growthData: days(28, 10),
    hashtags: ["#EldenRing", "#GamingChallenge", "#Blindfolded", "#GamingContent"],
  },
  {
    id: "t11",
    title: "Teaching My Grandma to Code with AI in 1 Hour",
    niche: "Education",
    platform: "TikTok",
    country: "Global",
    viralScore: 93,
    opportunityScore: 89,
    saturationLevel: "Low",
    trendVelocity: "Exploding",
    estimatedViews: 4_500_000,
    engagementRate: 15.3,
    hookPattern: "Unlikely student → AI as equalizer → heartwarming success",
    editingStyle: "Authentic, unfiltered, reaction cuts, natural lighting",
    audienceBehavior: "Massive shares, emotional comments, duet responses",
    growthData: days(30, 8),
    hashtags: ["#LearnToCode", "#AIForEveryone", "#Coding", "#Wholesome"],
  },
  {
    id: "t12",
    title: "Korean Street Food Hunt: $5 Budget Challenge",
    niche: "Lifestyle",
    platform: "Instagram",
    country: "Korea",
    viralScore: 81,
    opportunityScore: 90,
    saturationLevel: "Low",
    trendVelocity: "Rising",
    estimatedViews: 1_800_000,
    engagementRate: 10.4,
    hookPattern: "Budget constraint → exotic location → surprising value",
    editingStyle: "Vibrant food close-ups, handheld camera, authentic street sounds",
    audienceBehavior: "Save for travel, tag friends, comment food suggestions",
    growthData: days(16, 35),
    hashtags: ["#KoreanFood", "#StreetFood", "#FoodChallenge", "#Korea"],
  },
];

export const PLATFORMS = ["YouTube", "TikTok", "Instagram", "X", "Shorts", "Threads"] as const;
export const NICHES: string[] = ["All", "Tech", "AI", "Finance", "Investing", "Gaming", "Lifestyle", "Education", "Storytelling", "Comedy"];
export const COUNTRIES = ["Global", "USA", "Indonesia", "Japan", "Korea"] as const;
